### ISSUE TITLE
Building static dictionary data at run-time initialization

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/argo-docs#167] opened 2020-03-26 15:08 UTC
Pulling the data in at run-time initialization allows us to release new dictionary data by redeploying the doc sites without releasing a new version of it.

**Comment by rosibaj** [comment] 2020-04-07 15:35
@hlminh2000 is this a duplicate of #186 ?

**Comment by hlminh2000** [comment] 2020-04-07 15:38
not sure what #186 is, if it is for changing up the release process, then yes! :)

**Closed** 2020-04-07 16:23 UTC
Labels: duplicate, new-feature
